version: "3.9"

services:
  app:
    build: .
    container_name: weather_bot
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db/weather_db
    ports:
      - "80:80"
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
